### ISSUE TITLE
Add support for relative path of SSH key

### ISSUE THREAD

**Issue by idomingu** [davidfdezc/vnx#1]
VNX only allows absolute path when specifying SSH key.

Here is the line to be modified:

https://github.com/davidfdezc/vnx/blob/81010fc005852f09e874c406482a99d35237a3db/vnx-folder/perl-modules/VNX/CheckSemantics.pm#L260

**Comment by davidfdezc** [comment]
Solved. Additional minor changes were needed in vnx.pl to convert relative paths to absolute.

**Comment by davidfdezc** [comment]
Just update VNX with "vnx_update" command to get the new version with the modifications.

**Comment by idomingu** [comment]
Great, thanks!
